name: AWS CI

on: 
  push:
    branches:
        - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Set up AWS env
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # Set up gatsby and build it
      - name: Install dependencies and build site
        run: npm install && npm run build 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%F-%H:%M:%S)"
      - name: Rename old build folder then copy new one over
        run: |
          aws s3 mv s3://${BUCKET}/build s3://${BUCKET}/${FOLDER} --recursive
          aws s3 cp public/ s3://${BUCKET}/build --acl public-read --recursive
        env:
          BUCKET: codycline.com
          FOLDER: build_${{ steps.date.outputs.date }}
      - name: Invalidate current cloudfront distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*
